### ISSUE TITLE
Parsing error when using brackets `[` `]` in if conditions

### ISSUE THREAD

**Issue by primeapple** [ram02z/tree-sitter-fish#18]
The following results in an error:
```fish
if [ 1 -lt 2 ]
    echo 1
end
```

TSPlayground says: 
```
ERROR [0, 0] - [3, 0]
  argument: integer [0, 5] - [0, 6]
  argument: word [0, 7] - [0, 10]
  argument: integer [0, 11] - [0, 12]
  argument: word [0, 13] - [0, 14]
  argument: word [1, 4] - [1, 8]
  argument: integer [1, 9] - [1, 10]
  argument: word [2, 0] - [2, 3]
```

However it is in fact valid fish code :open_mouth:

**Comment by taekwombo** [comment]
Regexp at the end of this rule should never consume newline characters:
https://github.com/ram02z/tree-sitter-fish/blob/6675b56266b3f615fb112205b6b83a79315309c4/grammar.ts#L201

**Comment by taekwombo** [comment]
It was just a note (an entry point for later) to not search for the cause twice.
I will create PR with fix once I land on the final solution because there are two ways to solve this issue.

**Comment by primeapple** [comment]
So fast, you guys are awesome 😊
