### ISSUE TITLE
Allow `&|` and `2>|` in pipes

### ISSUE THREAD

**Issue by piechologist** [ram02z/tree-sitter-fish#20]
Is it possible to add `&|` and `2>|` as pipe operators? I'm thinking of something like:

```js
pipe: $ => prec.left(seq($._statement, choice('&|', '2>|', '|'), $._statement)),
```

I'm new to tree-sitter and I'm not sure if this may cause any side effects.

For reference: convenience operators in the [fish docs](https://fishshell.com/docs/current/language.html#piping)

**Comment by piechologist** [comment]
Is it possible to add `&|` and `2>|` as pipe operators?  I'm thinking of something like:

```js
pipe: $ => prec.left(seq($._statement, choice('&|', '2>|', '|'), $._statement)),
```

I'm new to tree-sitter and I'm not sure if this may cause any side effects.

For reference: convenience operators in the [fish docs](https://fishshell.com/docs/current/language.html#piping)

**Comment by taekwombo** [comment]
Yeah, just add the other alternatives to `|` here: https://github.com/ram02z/tree-sitter-fish/blob/master/grammar.ts#L87 just like you wrote.
And two more test cases here https://github.com/ram02z/tree-sitter-fish/blob/master/test/corpus/pipe.txt

**Comment by piechologist** [comment]
Works like a charm locally in the [Zed editor](https://github.com/zed-industries/zed). See PR #21. 

Let me know if I should make changes. Cheers!
