### ISSUE TITLE
Drop support for `^` in redirections

### ISSUE THREAD

**Issue by piechologist** [ram02z/tree-sitter-fish#22]
One more thing I noticed when playing around with the grammar:

I'm sure the caret `^` can be safely removed from `WORD_START_NEG_PATTERN` and `WORD_CONTINUE_NEG_PATTERN`. It doesn't have a special meaning since fish 3.5 and this repo targets fish 3.5.1.

> fish 3.5.0
> [Deprecations and removed features](https://fishshell.com/docs/current/relnotes.html#id17)
> 
> The stderr-nocaret feature flag, introduced in fish 3.0 and enabled by default in fish 3.1, has been made read-only. That means it is no longer possible to disable it, and code supporting the ^ redirection has been removed.

We could write unquoted expressions like
```fish
math 2 ^ 4
grep ^pattern foo
```
Currently, this results in an error.

I tested this locally and it looks good. There are no tests covering `^` and it's not used in the grammar anywhere else. I could make a PR if you agree.

**Comment by taekwombo** [comment]
Nice catch ;]
Feel free to provide any prs :+1:
