### ISSUE TITLE
Two issues with the comment query

### ISSUE THREAD

**Issue by gravndal** [ram02z/tree-sitter-fish#8]
See:
```fish
> echo (echo a b # comment) c d not#a#comment
a b c d not#a#comment

> echo not#a#comment (echo a b # comment) c d
not#a#comment a b c d
```

The parser currently treats everything after the first `#` in a line as a comment, this simple rule fails to match fish proper in at least two different contexts as seen above.

**Comment by taekwombo** [comment]
Similar issue in tree-sitter-bash: https://github.com/tree-sitter/tree-sitter-bash/issues/116
I suspect the solution to this issue would be the same in both repositories.
